In [107]:
import numpy as np
import pandas as pd

In [108]:
df = pd.read_csv("cleaned_Test.csv")

In [109]:
df_new = pd.DataFrame(data = df, columns = ["anne_sektor","baba_sektor"])

In [110]:
df_new = df_new.replace(['0', '-'], 'Unknown')

# Or alternatively, use NaN and fill later:
# data = data.replace(['0', '-'], pd.NA)

In [111]:
df_new

       anne_sektor  baba_sektor
0      ozel sektor        diger
1          Unknown  ozel sektor
2          Unknown      Unknown
3          Unknown  ozel sektor
4             kamu         kamu
...            ...          ...
11044      Unknown      Unknown
11045      Unknown         kamu
11046      Unknown        diger
11047      Unknown        diger
11048      Unknown  ozel sektor

[11049 rows x 2 columns]

In [112]:
from sklearn.preprocessing import LabelEncoder

# Apply label encoding
label_encoder = LabelEncoder()

# Encoding 'anne_sektor' and 'baba_sektor' columns
df_new['anne_sektor_encoded'] = label_encoder.fit_transform(df_new['anne_sektor'])
df_new['baba_sektor_encoded'] = label_encoder.fit_transform(df_new['baba_sektor'])

In [113]:
df_new = pd.get_dummies(df_new, columns=['anne_sektor', 'baba_sektor'], prefix=['anne', 'baba'], dummy_na=True)

In [114]:
df_new = df_new.drop(["anne_nan","baba_nan"],axis =1)
df_new

,anne_sektor_encoded,baba_sektor_encoded,anne_Unknown,anne_diger,anne_kamu,anne_ozel sektor,baba_Unknown,baba_diger,baba_kamu,baba_ozel sektor
0,3,1,False,False,False,True,False,True,False,False
1,0,3,True,False,False,False,False,False,False,True
2,0,0,True,False,False,False,True,False,False,False
3,0,3,True,False,False,False,False,False,False,True
4,2,2,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
11044,0,0,True,False,False,False,True,False,False,False
11045,0,2,True,False,False,False,False,False,True,False
11046,0,1,True,False,False,False,False,True,False,False
11047,0,1,True,False,False,False,False,True,False,False
11048,0,3,True,False,False,False,False,False,False,True

In [115]:
df=df.drop(["anne_sektor","baba_sektor"],axis =1)

In [116]:
cleanedData = pd.concat([df,df_new],axis = 1)
cleanedData

,basvuru_yili,cinsiyet,dogum_tarihi,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,...,anne_sektor_encoded,baba_sektor_encoded,anne_Unknown,anne_diger,anne_kamu,anne_ozel sektor,baba_Unknown,baba_diger,baba_kamu,baba_ozel sektor
0,2023,kadin,2002-06-21,amasya,amasya,munzur universitesi,devlet,0.0,0,sosyal hizmet,...,3,1,False,False,False,True,False,True,False,False
1,2023,kadin,2004-11-05,konya,konya,hacettepe universitesi,devlet,0.0,0,uluslararasi iliskiler,...,0,3,True,False,False,False,False,False,False,True
2,2023,erkek,2002-04-24,istanbul,istanbul,kapadokya universitesi,ozel,0.0,1,diger,...,0,0,True,False,False,False,True,False,False,False
3,2023,erkek,2003-11-03,mardin,mardin,mardin artuklu universitesi,devlet,0.0,0,islami ilimler,...,0,3,True,False,False,False,False,False,False,True
4,2023,erkek,2002-01-26,samsun,istanbul,bogazici universitesi,devlet,0.0,0,isletme,...,2,2,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,kadin,2002-03-01,yozgat,ankara,gazi universitesi,devlet,0.0,0,endustri muhendisligi,...,0,0,True,False,False,False,True,False,False,False
11045,2023,kadin,2001-09-09,konya,konya,nigde omer halisdemir universitesi,devlet,0.0,0,gida muhendisligi,...,0,2,True,False,False,False,False,False,True,False
11046,2023,erkek,2004-08-06,ankara,ankara,karabuk universitesi,devlet,0.0,0,elektrik-elektronik muhendisligi,...,0,1,True,False,False,False,False,True,False,False
11047,2023,kadin,2001-10-16,adiyaman,istanbul,bursa uludag universitesi,devlet,0.0,0,"molekuler biyoloji, genetik ve biyomuhendislik",...,0,1,True,False,False,False,False,True,False,False
11048,2023,kadin,1999-09-22,nigde,ankara,hacettepe universitesi,devlet,0.0,0,endustri muhendisligi,...,0,3,True,False,False,False,False,False,False,True

In [117]:
cleanedData['cinsiyet'] = cleanedData['cinsiyet'].map({'erkek': 0, 'kadin': 1 ,"Belirtmek istemiyorum":-1})

In [118]:
cleanedData

,basvuru_yili,cinsiyet,dogum_tarihi,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,...,anne_sektor_encoded,baba_sektor_encoded,anne_Unknown,anne_diger,anne_kamu,anne_ozel sektor,baba_Unknown,baba_diger,baba_kamu,baba_ozel sektor
0,2023,1.0,2002-06-21,amasya,amasya,munzur universitesi,devlet,0.0,0,sosyal hizmet,...,3,1,False,False,False,True,False,True,False,False
1,2023,1.0,2004-11-05,konya,konya,hacettepe universitesi,devlet,0.0,0,uluslararasi iliskiler,...,0,3,True,False,False,False,False,False,False,True
2,2023,0.0,2002-04-24,istanbul,istanbul,kapadokya universitesi,ozel,0.0,1,diger,...,0,0,True,False,False,False,True,False,False,False
3,2023,0.0,2003-11-03,mardin,mardin,mardin artuklu universitesi,devlet,0.0,0,islami ilimler,...,0,3,True,False,False,False,False,False,False,True
4,2023,0.0,2002-01-26,samsun,istanbul,bogazici universitesi,devlet,0.0,0,isletme,...,2,2,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,1.0,2002-03-01,yozgat,ankara,gazi universitesi,devlet,0.0,0,endustri muhendisligi,...,0,0,True,False,False,False,True,False,False,False
11045,2023,1.0,2001-09-09,konya,konya,nigde omer halisdemir universitesi,devlet,0.0,0,gida muhendisligi,...,0,2,True,False,False,False,False,False,True,False
11046,2023,0.0,2004-08-06,ankara,ankara,karabuk universitesi,devlet,0.0,0,elektrik-elektronik muhendisligi,...,0,1,True,False,False,False,False,True,False,False
11047,2023,1.0,2001-10-16,adiyaman,istanbul,bursa uludag universitesi,devlet,0.0,0,"molekuler biyoloji, genetik ve biyomuhendislik",...,0,1,True,False,False,False,False,True,False,False
11048,2023,1.0,1999-09-22,nigde,ankara,hacettepe universitesi,devlet,0.0,0,endustri muhendisligi,...,0,3,True,False,False,False,False,False,False,True

In [119]:
cleanedData.to_csv("cleanedData.csv")

In [120]:
from datetime import datetime

In [121]:
cleanedData['dogum_tarihi'] = pd.to_datetime(cleanedData['dogum_tarihi'])

# Extract the year of birth
cleanedData['birth_year'] = cleanedData['dogum_tarihi'].dt.year
cleanedData['age'] = 2024 - cleanedData['birth_year']
cleanedData["age"]

0        22
1        20
2        22
3        21
4        22
         ..
11044    22
11045    23
11046    20
11047    23
11048    25
Name: age, Length: 11049, dtype: int32

In [122]:
cleanedData = cleanedData.drop(["birth_year","dogum_tarihi"],axis =1)

In [123]:
cleanedData.to_csv("cleanTest.csv")

In [124]:
list = []
for columns in cleanedData:
    list.append(columns)
list

['basvuru_yili',
 'cinsiyet',
 'dogum_yeri',
 'ikametgah_sehri',
 'universite_adi',
 'universite_turu',
 'burslu_ise_burs_yuzdesi',
 'burs_aliyor_mu?',
 'bolum',
 'universite_kacinci_sinif',
 'universite_not_ortalamasi',
 'daha_once_baska_bir_universiteden_mezun_olmus',
 'lise_adi',
 'lise_adi_diger',
 'lise_sehir',
 'lise_turu',
 'lise_bolumu',
 'lise_bolum_diger',
 'lise_mezuniyet_notu',
 'baska_bir_kurumdan_burs_aliyor_mu?',
 'burs_aldigi_baska_kurum',
 'baska_kurumdan_aldigi_burs_miktari',
 'anne_egitim_durumu',
 'anne_calisma_durumu',
 'baba_egitim_durumu',
 'baba_calisma_durumu',
 'kardes_sayisi',
 'girisimcilik_kulupleri_tarzi_bir_kulube_uye_misiniz?',
 'uye_oldugunuz_kulubun_ismi',
 'profesyonel_bir_spor_daliyla_mesgul_musunuz?',
 'spor_dalindaki_rolunuz_nedir?',
 'aktif_olarak_bir_stk_uyesi_misiniz?',
 "hangi_stk'nin_uyesisiniz?",
 'stk_projesine_katildiniz_mi?',
 'girisimcilikle_ilgili_deneyiminiz_var_mi?',
 'girisimcilikle_ilgili_deneyiminizi_aciklayabilir_misiniz?',
 'ingilizce_biliyor_musunuz?',
 'ingilizce_seviyeniz?',
 'daha_onceden_mezun_olunduysa,_mezun_olunan_universite',
 'id',
 'anne_sektor_encoded',
 'baba_sektor_encoded',
 'anne_Unknown',
 'anne_diger',
 'anne_kamu',
 'anne_ozel sektor',
 'baba_Unknown',
 'baba_diger',
 'baba_kamu',
 'baba_ozel sektor',
 'age']

In [125]:
cleanedData

,basvuru_yili,cinsiyet,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,universite_kacinci_sinif,...,baba_sektor_encoded,anne_Unknown,anne_diger,anne_kamu,anne_ozel sektor,baba_Unknown,baba_diger,baba_kamu,baba_ozel sektor,age
0,2023,1.0,amasya,amasya,munzur universitesi,devlet,0.0,0,sosyal hizmet,1,...,1,False,False,False,True,False,True,False,False,22
1,2023,1.0,konya,konya,hacettepe universitesi,devlet,0.0,0,uluslararasi iliskiler,1,...,3,True,False,False,False,False,False,False,True,20
2,2023,0.0,istanbul,istanbul,kapadokya universitesi,ozel,0.0,1,diger,1,...,0,True,False,False,False,True,False,False,False,22
3,2023,0.0,mardin,mardin,mardin artuklu universitesi,devlet,0.0,0,islami ilimler,1,...,3,True,False,False,False,False,False,False,True,21
4,2023,0.0,samsun,istanbul,bogazici universitesi,devlet,0.0,0,isletme,3,...,2,False,False,True,False,False,False,True,False,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,1.0,yozgat,ankara,gazi universitesi,devlet,0.0,0,endustri muhendisligi,2,...,0,True,False,False,False,True,False,False,False,22
11045,2023,1.0,konya,konya,nigde omer halisdemir universitesi,devlet,0.0,0,gida muhendisligi,3,...,2,True,False,False,False,False,False,True,False,23
11046,2023,0.0,ankara,ankara,karabuk universitesi,devlet,0.0,0,elektrik-elektronik muhendisligi,1,...,1,True,False,False,False,False,True,False,False,20
11047,2023,1.0,adiyaman,istanbul,bursa uludag universitesi,devlet,0.0,0,"molekuler biyoloji, genetik ve biyomuhendislik",4,...,1,True,False,False,False,False,True,False,False,23
11048,2023,1.0,nigde,ankara,hacettepe universitesi,devlet,0.0,0,endustri muhendisligi,4,...,3,True,False,False,False,False,False,False,True,25