In [325]:
import numpy as np
import pandas as pd

In [326]:
df = pd.read_csv("test_clean.csv")

In [327]:
df_new = pd.DataFrame(data = df, columns = ["anne_sektor","baba_sektor"])

In [328]:
df_new = df_new.replace(['0', '-'], 'Unknown')

# Or alternatively, use NaN and fill later:
# data = data.replace(['0', '-'], pd.NA)

In [329]:
df_new

       anne_sektor  baba_sektor
0      ozel Sektor        Diger
1          Unknown  ozel Sektor
2          Unknown      Unknown
3          Unknown  ozel Sektor
4             Kamu         Kamu
...            ...          ...
11044      Unknown      Unknown
11045      Unknown         Kamu
11046      Unknown        Diger
11047      Unknown        Diger
11048      Unknown  ozel Sektor

[11049 rows x 2 columns]

In [330]:
from sklearn.preprocessing import LabelEncoder

# Apply label encoding
label_encoder = LabelEncoder()

# Encoding 'anne_sektor' and 'baba_sektor' columns
df_new['anne_sektor_encoded'] = label_encoder.fit_transform(df_new['anne_sektor'])
df_new['baba_sektor_encoded'] = label_encoder.fit_transform(df_new['baba_sektor'])

In [331]:
df_new = pd.get_dummies(df_new, columns=['anne_sektor', 'baba_sektor'], prefix=['anne', 'baba'], dummy_na=True)

In [332]:
df_new = df_new.drop(["anne_nan","baba_nan"],axis =1)
df_new

,anne_sektor_encoded,baba_sektor_encoded,anne_Diger,anne_Kamu,anne_Unknown,anne_ozel Sektor,baba_Diger,baba_Kamu,baba_Unknown,baba_ozel Sektor
0,3,0,False,False,False,True,True,False,False,False
1,2,3,False,False,True,False,False,False,False,True
2,2,2,False,False,True,False,False,False,True,False
3,2,3,False,False,True,False,False,False,False,True
4,1,1,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
11044,2,2,False,False,True,False,False,False,True,False
11045,2,1,False,False,True,False,False,True,False,False
11046,2,0,False,False,True,False,True,False,False,False
11047,2,0,False,False,True,False,True,False,False,False
11048,2,3,False,False,True,False,False,False,False,True

In [333]:
df=df.drop(["anne_sektor","baba_sektor"],axis =1)

In [334]:
cleanedData = pd.concat([df,df_new],axis = 1)
cleanedData

,basvuru_yili,cinsiyet,dogum_tarihi,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,...,anne_sektor_encoded,baba_sektor_encoded,anne_Diger,anne_Kamu,anne_Unknown,anne_ozel Sektor,baba_Diger,baba_Kamu,baba_Unknown,baba_ozel Sektor
0,2023,Kadin,2002-06-21,Amasya,Amasya,Munzur universitesi,Devlet,0.0,Hayir,Sosyal Hizmet,...,3,0,False,False,False,True,True,False,False,False
1,2023,Kadin,2004-11-05,Konya,Konya,Hacettepe universitesi,Devlet,0.0,Hayir,Uluslararasi Ä°liskiler,...,2,3,False,False,True,False,False,False,False,True
2,2023,Erkek,2002-04-24,Ä°stanbul,Ä°stanbul,Kapadokya universitesi,ozel,0.0,Evet,Diger,...,2,2,False,False,True,False,False,False,True,False
3,2023,Erkek,2003-11-03,Mardin,Mardin,Mardin Artuklu universitesi,Devlet,0.0,Hayir,Ä°slami Ä°limler,...,2,3,False,False,True,False,False,False,False,True
4,2023,Erkek,2002-01-26,Samsun,Ä°stanbul,Bogazici universitesi,Devlet,0.0,Hayir,Ä°sletme,...,1,1,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,Kadin,2002-03-01,Yozgat,Ankara,Gazi universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,...,2,2,False,False,True,False,False,False,True,False
11045,2023,Kadin,2001-09-09,Konya,Konya,Nigde omer Halisdemir universitesi,Devlet,0.0,Hayir,Gida Muhendisligi,...,2,1,False,False,True,False,False,True,False,False
11046,2023,Erkek,2004-08-06,Ankara,Ankara,Karabuk universitesi,Devlet,0.0,Hayir,Elektrik-Elektronik Muhendisligi,...,2,0,False,False,True,False,True,False,False,False
11047,2023,Kadin,2001-10-16,Adiyaman,Ä°stanbul,Bursa Uludag universitesi,Devlet,0.0,Hayir,"Molekuler Biyoloji, Genetik ve Biyomuhendislik",...,2,0,False,False,True,False,True,False,False,False
11048,2023,Kadin,1999-09-22,Nigde,Ankara,Hacettepe universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,...,2,3,False,False,True,False,False,False,False,True

In [335]:
cleanedData['cinsiyet'] = cleanedData['cinsiyet'].map({'Erkek': 0, 'Kadin': 1 ,"Belirtmek istemiyorum":-1})

In [336]:
cleanedData

,basvuru_yili,cinsiyet,dogum_tarihi,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,...,anne_sektor_encoded,baba_sektor_encoded,anne_Diger,anne_Kamu,anne_Unknown,anne_ozel Sektor,baba_Diger,baba_Kamu,baba_Unknown,baba_ozel Sektor
0,2023,1,2002-06-21,Amasya,Amasya,Munzur universitesi,Devlet,0.0,Hayir,Sosyal Hizmet,...,3,0,False,False,False,True,True,False,False,False
1,2023,1,2004-11-05,Konya,Konya,Hacettepe universitesi,Devlet,0.0,Hayir,Uluslararasi Ä°liskiler,...,2,3,False,False,True,False,False,False,False,True
2,2023,0,2002-04-24,Ä°stanbul,Ä°stanbul,Kapadokya universitesi,ozel,0.0,Evet,Diger,...,2,2,False,False,True,False,False,False,True,False
3,2023,0,2003-11-03,Mardin,Mardin,Mardin Artuklu universitesi,Devlet,0.0,Hayir,Ä°slami Ä°limler,...,2,3,False,False,True,False,False,False,False,True
4,2023,0,2002-01-26,Samsun,Ä°stanbul,Bogazici universitesi,Devlet,0.0,Hayir,Ä°sletme,...,1,1,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,1,2002-03-01,Yozgat,Ankara,Gazi universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,...,2,2,False,False,True,False,False,False,True,False
11045,2023,1,2001-09-09,Konya,Konya,Nigde omer Halisdemir universitesi,Devlet,0.0,Hayir,Gida Muhendisligi,...,2,1,False,False,True,False,False,True,False,False
11046,2023,0,2004-08-06,Ankara,Ankara,Karabuk universitesi,Devlet,0.0,Hayir,Elektrik-Elektronik Muhendisligi,...,2,0,False,False,True,False,True,False,False,False
11047,2023,1,2001-10-16,Adiyaman,Ä°stanbul,Bursa Uludag universitesi,Devlet,0.0,Hayir,"Molekuler Biyoloji, Genetik ve Biyomuhendislik",...,2,0,False,False,True,False,True,False,False,False
11048,2023,1,1999-09-22,Nigde,Ankara,Hacettepe universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,...,2,3,False,False,True,False,False,False,False,True

In [337]:
cleanedData.to_csv("cleanedData.csv")

In [338]:
from datetime import datetime

In [339]:
cleanedData['dogum_tarihi'] = pd.to_datetime(cleanedData['dogum_tarihi'])

# Extract the year of birth
cleanedData['birth_year'] = cleanedData['dogum_tarihi'].dt.year
cleanedData['age'] = 2024 - cleanedData['birth_year']
cleanedData["age"]

0        22
1        20
2        22
3        21
4        22
         ..
11044    22
11045    23
11046    20
11047    23
11048    25
Name: age, Length: 11049, dtype: int32

In [340]:
cleanedData = cleanedData.drop(["birth_year","dogum_tarihi"],axis =1)

In [341]:
cleanedData.to_csv("cleanedTest.csv")

In [342]:
list = []
for columns in cleanedData:
    list.append(columns)
list

['basvuru_yili',
 'cinsiyet',
 'dogum_yeri',
 'ikametgah_sehri',
 'universite_adi',
 'universite_turu',
 'burslu_ise_burs_yuzdesi',
 'burs_aliyor_mu?',
 'bolum',
 'universite_kacinci_sinif',
 'universite_not_ortalamasi',
 'daha_once_baska_bir_universiteden_mezun_olmus',
 'lise_adi',
 'lise_adi_diger',
 'lise_sehir',
 'lise_turu',
 'lise_bolumu',
 'lise_bolum_diger',
 'lise_mezuniyet_notu',
 'baska_bir_kurumdan_burs_aliyor_mu?',
 'burs_aldigi_baska_kurum',
 'baska_kurumdan_aldigi_burs_miktari',
 'anne_egitim_durumu',
 'anne_calisma_durumu',
 'baba_egitim_durumu',
 'baba_calisma_durumu',
 'kardes_sayisi',
 'girisimcilik_kulupleri_tarzi_bir_kulube_uye_misiniz?',
 'uye_oldugunuz_kulubun_ismi',
 'profesyonel_bir_spor_daliyla_mesgul_musunuz?',
 'spor_dalindaki_rolunuz_nedir?',
 'aktif_olarak_bir_stk_uyesi_misiniz?',
 "hangi_stk'nin_uyesisiniz?",
 'stk_projesine_katildiniz_mi?',
 'girisimcilikle_ilgili_deneyiminiz_var_mi?',
 'girisimcilikle_ilgili_deneyiminizi_aciklayabilir_misiniz?',
 'ingilizce_biliyor_musunuz?',
 'ingilizce_seviyeniz?',
 'daha_onceden_mezun_olunduysa,_mezun_olunan_universite',
 'id',
 'anne_sektor_encoded',
 'baba_sektor_encoded',
 'anne_Diger',
 'anne_Kamu',
 'anne_Unknown',
 'anne_ozel Sektor',
 'baba_Diger',
 'baba_Kamu',
 'baba_Unknown',
 'baba_ozel Sektor',
 'age']

In [343]:
cleanedData

,basvuru_yili,cinsiyet,dogum_yeri,ikametgah_sehri,universite_adi,universite_turu,burslu_ise_burs_yuzdesi,burs_aliyor_mu?,bolum,universite_kacinci_sinif,...,baba_sektor_encoded,anne_Diger,anne_Kamu,anne_Unknown,anne_ozel Sektor,baba_Diger,baba_Kamu,baba_Unknown,baba_ozel Sektor,age
0,2023,1,Amasya,Amasya,Munzur universitesi,Devlet,0.0,Hayir,Sosyal Hizmet,1,...,0,False,False,False,True,True,False,False,False,22
1,2023,1,Konya,Konya,Hacettepe universitesi,Devlet,0.0,Hayir,Uluslararasi Ä°liskiler,1,...,3,False,False,True,False,False,False,False,True,20
2,2023,0,Ä°stanbul,Ä°stanbul,Kapadokya universitesi,ozel,0.0,Evet,Diger,1,...,2,False,False,True,False,False,False,True,False,22
3,2023,0,Mardin,Mardin,Mardin Artuklu universitesi,Devlet,0.0,Hayir,Ä°slami Ä°limler,1,...,3,False,False,True,False,False,False,False,True,21
4,2023,0,Samsun,Ä°stanbul,Bogazici universitesi,Devlet,0.0,Hayir,Ä°sletme,3,...,1,False,True,False,False,False,True,False,False,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,2023,1,Yozgat,Ankara,Gazi universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,2,...,2,False,False,True,False,False,False,True,False,22
11045,2023,1,Konya,Konya,Nigde omer Halisdemir universitesi,Devlet,0.0,Hayir,Gida Muhendisligi,3,...,1,False,False,True,False,False,True,False,False,23
11046,2023,0,Ankara,Ankara,Karabuk universitesi,Devlet,0.0,Hayir,Elektrik-Elektronik Muhendisligi,1,...,0,False,False,True,False,True,False,False,False,20
11047,2023,1,Adiyaman,Ä°stanbul,Bursa Uludag universitesi,Devlet,0.0,Hayir,"Molekuler Biyoloji, Genetik ve Biyomuhendislik",4,...,0,False,False,True,False,True,False,False,False,23
11048,2023,1,Nigde,Ankara,Hacettepe universitesi,Devlet,0.0,Hayir,Endustri Muhendisligi,4,...,3,False,False,True,False,False,False,False,True,25